<?php
/**
 * Created by PhpStorm.
 * User: vivma
 * Date: 12/03/2017
 * Time: 22:08
 */

namespace AppBundle\Repository;

use AppBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /* Retourne les 10 derniers posts ajoutés en base de données
     * @param int $maxResult
     * @return Post[]
     */
    public function getLastPost($maxResult = 10)
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->orderBy('t.createdAt', 'DESC')
            ->setMaxResults($maxResult)
            ->getQuery()
            ->getResult();
    }
    public function getActivesPostsByUser(User $user)
    {
        return $this->createQueryBuilder('p')
            ->select('p')
           ->andWhere('p.status = :status')
            ->andWhere('p.author = :author')
            ->setParameter('status', Post::STATUS_ACTIVE)
            ->setParameter('author',$user->getId())
            ->getQuery()
            ->getResult();
    }
    /* Retourne le post d'id $id
     * @param int $id
     * @return Post
     */
    public function getPost($id)
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->andWhere('p.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}