# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.post_manager:
            class: AppBundle\Manager\PostManager
            arguments:
                  - "@=service('doctrine').getManager()"

    app.avatar_manager:
        class: AppBundle\Manager\AvatarUserResolver
        arguments:
            - "@=service('doctrine').getManager()"

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.twig.avatar_extension:
        class: AppBundle\Twig\AvatarExtension
        tags:
        - { name: twig.extension }
        arguments:
            - "@app.avatar_manager"